package com.piketalks.beservicejava.model;

import jdk.internal.jline.internal.Nullable;
import lombok.*;

import javax.persistence.*;
import javax.validation.constraints.NotNull;
import java.time.Instant;

@Data //Getter/setters are generated by Lombok
@Entity //JPA entity
@Builder //Use builder pattern
@AllArgsConstructor //Use all arg constructor for builder
@NoArgsConstructor //Use no arg constructor
public class Post {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long postId;
    //@NotBlank(message = "Post Name shall not be empty/Null")
    @NotNull
    private String postName;
    @Nullable
    private String url;
    @Nullable
    @Lob //Large chunk of data managed with Lob
    private String description;
    private Integer voteCount;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "userId", referencedColumnName = "userId")
    private User user;
    private Instant createdDate;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id", referencedColumnName = "id")
    private Subtalk subtalk;
}
